Characterization output are large - introduce minimum proportion
OHDSI/CohortDiagnostics pull request #904
Opened 2022-08-19 19:00 UTC by gowthamrao

to reduce the file size

We already had this parameter called cutoff in exportCharacterization. So it is not a new functionality. This PR just makes it more transparent and available to the end user, instead of being hard coded.

Ideally should be in Feature Extraction. Then it can be filtered at the database level, instead of at the client level https://github.com/OHDSI/FeatureExtraction/issues/174

2022-08-24 17:54 UTC, azimov requested changes

2022-08-24 21:10 UTC, gowthamrao commented on R/RunDiagnostics.R
> +#' @param minCharacterizationMean     The minimum mean value for characterization output. Values below this will be cut off from output.
Looks like it does not like % sign. Ooh well. Now fixed

thanks @azimov

2022-08-26 17:41 UTC, azimov requested changes
Please add a line to NEWS.md describing the changes made

2022-08-26 17:45 UTC, azimov commented
Out of interest, do you have an example of how much this reduces the output file size?

2022-08-26 23:04 UTC, gowthamrao commented
> Out of interest, do you have an example of how much this reduces the output file size?

almost 10x reduction !

2022-08-29 17:35 UTC, azimov approved these changes

2022-08-29 17:35 UTC, merged